name: jinja
description: >-
  Jinja2 server-side template engine for Dart.
  Variables, expressions, control structures and template inheritance.
version: 0.2.3
homepage: https://github.com/ykmnkmi/jinja.dart

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  meta: ^1.1.8
  path: ^1.6.4
  string_scanner: ^1.0.5

dev_dependencies:
  angular_ast: ^0.5.11
  pedantic: ^1.9.0
  test: ^1.11.0
