name: jinja
description: >-
  Jinja2 template engine for Dart.
  Variables, expressions, control structures and template inheritance.
homepage: https://github.com/ykmnkmi/jinja.dart
version: 0.4.0-dev.58

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  meta: ^1.8.0
  path: ^1.8.0
  string_scanner: ^1.2.0
  textwrap: ^1.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
