name: jinja
version: 0.6.0-dev.0
description: >-
  Jinja2 template engine for Dart.
  Variables, expressions, control structures and template inheritance.
repository: https://github.com/ykmnkmi/jinja.dart
funding:
  - https://www.buymeacoffee.com/ykmnkmi

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  html_unescape: ^2.0.0
  meta: ^1.9.1
  path: ^1.8.3
  string_scanner: ^1.2.0
  textwrap: ^1.2.0

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.4
